trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Angular and Spring Boot Applications'
  steps:
    - task: Checkout@1
      displayName: 'Checkout Repository'

    - script: |
        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
      displayName: 'Setup Node.js'

    - script: |
        cd frontend/
        npm install
        npm run build --prod
      displayName: 'Build Angular Application'

    - script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
      displayName: 'Setup Java'

    - script: |
        cd backend/
        chmod +x mvnw
        ./mvnw clean install -DskipTests
      displayName: 'Build Spring Boot Application'
